### ISSUE TITLE
window.location.origin is not supported

### ISSUE THREAD

**Issue by vsemozhetbyt** [warren-bank/moz-rewrite#4]
Could you please add the .origin property to request.window_location ?

https://developer.mozilla.org/en-US/docs/Web/API/Location

https://developer.mozilla.org/en-US/docs/Web/API/URLUtils/origin

It would be very useful for CORS headers modification.

**Comment by warren-bank** [comment]
Hi. Thanks for the suggestion! My answer will need to be two-part.
1. Absolutely..<br>It would be extremely simple to include that property when building the `window_location` object within the ["get_window_components"](https://raw.githubusercontent.com/warren-bank/moz-rewrite/js/Cu.evalInSandbox/master/components/03_monolithic_addon/moz-rewrite.js) function.
2. The `window_location` object may need to be deprecated very soon. As soon as Firefox enforces [multi-process](https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox) (e10s), I'll need to rethink how this object is constructed. I'll either come up with some workaround (involving round-trip message passing between the addon and a "frame" script) or just remove the object altogether. It's been rattling around in the back of my mind. This will also effect the way the "redirectTo" function is implemented. I haven't given the addon any attention in a while, but if I want it to work in upcoming versions of Firefox.. then at some point in the near future, I'll need to dig into these e10s issues.

To get myself started, I think I'll add a new branch: `js/Cu.evalInSandbox/e10s`. I can certainly add a quick commit that will incorporate your feature request. I'll also re-implement "redirectTo"; it can (and should) be done entirely within the connection stream.. but I remember when I initially wrote it that way.. my tests failed to work properly.. and the current implementation was a workaround.. though (strictly speaking) it only works (as intended) for a very specific use case.. specifically, when the `url` being matched also happens to be the `url` of the webpage being loaded.. otherwise, we're redirecting the browser window based on the presence of some asset (ex: css file, image, etc).. which really wouldn't make any sense to do. In any case, with this branch in place.. I'll be more likely to put some effort into ironing out the remaining e10s issues.

I'll let you know when the first commit (and .xpi) is available. However, since the releases from this new branch won't be submit to AMO (addons.mozilla.org) for quite a while.. and since Firefox is now [enforcing signed extensions](https://blog.mozilla.org/addons/2015/06/18/compatibility-for-firefox-40/), you'll need to run the (experimental) addon in version <=39, or version 40 with the preference `xpinstall.signatures.required` updated to `false`. Version 41 will remove the ability to override this value.

**Comment by vsemozhetbyt** [comment]
Thank you a lot for the answer. Luckily I can replace this property with `request.headers.unmodified['origin']` now and will be able to do so if you give up on the `window_location`.

By the way, I have understood it must be the `request.headers.unmodified['origin']`, not the `request.headers.unmodified['Origin']` only after checking the saved request. Could you please emphasize in the help using the lowercase heder name here? Because all the HTTP docs and MDN docs use capitalized header names.

**Comment by warren-bank** [comment]
the README is a bit long, so some of the more obscure details may be difficult to find.
this particular detail is under the section: ["Hidden Preferences"](https://github.com/warren-bank/moz-rewrite#user-content-hidden-preferences),
where it discusses `extensions.Moz-Rewrite.case_sensitive`,
and the effect that the default value has on normalizing the names of headers to lowercase.

**Comment by warren-bank** [comment]
oops.. I have to correct myself on that..
if you look at the function: ["get_HTTP_headers"](https://raw.githubusercontent.com/warren-bank/moz-rewrite/js/Cu.evalInSandbox/master/components/03_monolithic_addon/moz-rewrite.js),
you'll see that the following statement is commented out:

> `if (! self.is_case_sensitive) header_key = header_key.toLowerCase()`

At one point, the preference that I mentioned controlled the normalization of both:
- URL property values
- HTTP header property names

But, I must have decided at some point that I couldn't think of any possible reason to not normalize the property names. To do so would create too many potential problems.

**examples**:
1. the case of the headers defined in the rules file doesn't match the case of the headers returned by the server
2. two or more rules match a given url, and the case of the headers they define differ. If the intention was for subsequent rules to override earlier rules, then the actual result would be undefined (since there is no guaranteed order while iterating over the properties of an object).

It makes sense to me why I chose to force the header properties to be lowercase.
And you're right, this should be better documented. :)

**Comment by vsemozhetbyt** [comment]
Thanks again)
